- name: Install NTP
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp
  tags:
    - packages
    - ntp

- name: Enable ntp
  service:
    name: ntp
    enabled: true
    state: started
  tags:
    - ntp
